# Configuracion especifica para team-masterdata (todos los entornos)
server:
  port: 8083

spring:
  jpa:
    properties:
      hibernate:
        default_schema: teamclub

  sql:
    init:
      data-locations: classpath:db/data.sql
