# Configuracion especifica de team-masterdata
server:
  port: 8083

spring:
  jpa:
    properties:
      hibernate:
        default_schema: teamclub_masterdata

  sql:
    init:
      data-locations: classpath:db/data.sql

  cloud:
    vault:
      kv:
        application-name: team-masterdata
