# Configuracion especifica para traductor-manager (todos los entornos)
server:
  port: 8084

spring:
  jpa:
    properties:
      hibernate:
        default_schema: teamclub

  sql:
    init:
      data-locations: classpath:db/data.sql
