# Configuracion especifica de usuario-manager
server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=teamclub

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_schema: teamclub

  sql:
    init:
      mode: always

# internal.api-key viene de Vault
