# Configuración común para entorno LOCAL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=teamclub
    username: postgres
    password: eduardo

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: teamclub
        globally_quoted_identifiers: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

logging:
  level:
    com.wakana.teamclub: DEBUG
    org.hibernate.SQL: DEBUG
