server:
  port: 8081

spring:
  jpa:
    properties:
      hibernate:
        default_schema: teamclub_auth

  cloud:
    vault:
      kv:
        application-name: auth-manager


# internal.api-key viene de Vault

security:
  jwt:
    issuer: wakana-teamclub-auth
    expires-minutes: 60
    # secret viene de Vault
