server:
  port: 8084

spring:
  jpa:
    properties:
      hibernate:
        default_schema: teamclub_traductor

  sql:
    init:
      data-locations: classpath:db/data.sql

  cloud:
    vault:
      kv:
        application-name: traductor-manager

# internal.api-key viene de Vault
