# Configuración común para entorno DEV
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-manager:8081/.well-known/jwks.json

logging:
  level:
    org.springframework.security: DEBUG
    com.wakana.teamclub: DEBUG
