# Configuracion comun para entorno DEV
# Sobrescribe valores de global/application.yml si es necesario
# Los secretos (username, password, api-keys) vienen de Vault

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=teamclub

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json
