# Configuracion de desarrollo para auth-manager
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=teamclub
    username: postgres
    password: eduardo

clients:
  usuario-manager:
    url: http://localhost:8082
sql:
  init:
    mode: always
    data-locations: classpath:db/data.sql
    continue-on-error: false
