# Configuracion de desarrollo para club-manager
# Los secretos (username, password) vienen de Vault
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=teamclub_club

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

clients:
  team-masterdata:
    url: http://localhost:8083
