# Perfil dev: conecta al Config Server (sin Vault, secretos directos)
server:
  port: 8085

spring:
  cloud:
    config:
      enabled: true
    vault:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=teamclub_club

  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      continue-on-error: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: teamclub_club
        globally_quoted_identifiers: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

clients:
  team-masterdata:
    url: http://localhost:8083
