# Configuracion de desarrollo para team-masterdata
# Los secretos (username, password) vienen de Vault
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=teamclub_masterdata

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json
