# Configuración común para entorno PRU (Pruebas)
spring:
  datasource:
    url: jdbc:postgresql://pru-db.teamclub.local:5432/teamclub_pru?currentSchema=teamclub
    username: teamclub_pru
    password: pru_password_changeme

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: teamclub
        globally_quoted_identifiers: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-manager:8081/.well-known/jwks.json

logging:
  level:
    com.wakana.teamclub: INFO
